<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Datoshoja;

class DatosHojaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Datoshoja::create([
            'titulo' => 'Checklist de contaminacion',
            'subtitulo' => 'Op. 00 Practicas de cuarto limpio',
            'documentoid' => 'F7-SETCS-ELE-CR-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / P. Uvalle',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Emmanuel Lopez',
            'area' => 'Cuarto Limpio 1',
            'linea' => '1',
            'operacion' => 0,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/972/971/959',
            'pagina' => '1 de 1',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de Cuarto Limpio',
            'subtitulo' => 'Op. 20 Normalizado',
            'documentoid' => 'F7-SETCS-ELE-20-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / E. Lopez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio 1',
            'linea' => '1',
            'operacion' => 20,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 3',
            'numeroparte' => 'Ver F2-FM-ELE-20-L1-01',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo Etiquetado de Material',
            'subtitulo' => 'Op. 20 Normalizado',
            'documentoid' => 'F7-SETCS-ELE-20-L1-03',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / E. Lopez',
            'calidad' => 'R. Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio 1',
            'linea' => '1',
            'operacion' => 20,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 3',
            'numeroparte' => 'Ver F2-FM-ELE-20-L1-01',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo',
            'subtitulo' => 'Op. 40 Ponchado de hojas',
            'documentoid' => 'F7-SETCS-ELE-40-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 40,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 3',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
                Datoshoja::create([
            'titulo' => 'Checklist Errorproofing',
            'subtitulo' => 'Op. 40 Ponchado de hojas',
            'documentoid' => 'F7-SETCS-ELE-40-L1-02',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'C. Perez / Ulises Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza / M. Espino',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 40,
            'lugar' => 'Torreon',
            'planta' => 'Plt 59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Parametros de Impresora',
            'subtitulo' => 'Op. 60 Impresion',
            'documentoid' => 'F7-SETCS-ELE-60-L1-06',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes / C. Perez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza / Irineo Lopez',
            'area' => 'Cuarto Limpio',
            'linea' => 'OSP111/NH3/PM/OSM/PM RTD/OSL/OSMa/OSMaG2',
            'operacion' => 60,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '959/971/972/970/926/975',
            'pagina' => '1 of 6',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Parametros de Impresora',
            'subtitulo' => 'Op. 60 Impresion',
            'documentoid' => 'F7-SETCS-ELE-60-L1-06-2',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes / C. Perez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza / Irineo Lopez',
            'area' => 'Cuarto Limpio',
            'linea' => 'OSP111/NH3/PM/OSM/PM RTD/OSL/OSMa/OSMaG2',
            'operacion' => 60,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '959/971/972/970/926/975',
            'pagina' => '1 of 6',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Medicion de localizacion de Impresion (OSMa)',
            'subtitulo' => 'Op. 60 Print',
            'documentoid' => 'F7-SETCS-ELE-60-L1-08',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'R. Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => 'OSMa',
            'operacion' => 60,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => 'OSMa',
            'pagina' => '1 of 1',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Parametros de Secador',
            'subtitulo' => 'Op. 100 Secado',
            'documentoid' => 'F7-SETCS-ELE-100-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Cuarto Limpio 1',
            'linea' => 'Secador AMI 1',
            'operacion' => 100,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '926/970/959/971/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Parametros de Secador',
            'subtitulo' => 'Op. 100 Secado',
            'documentoid' => 'F7-SETCS-ELE-100-L1-02',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Cuarto Limpio 1',
            'linea' => 'Secador Microtec',
            'operacion' => 100,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '926/970/959/971/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Verificacion de Parametros de Secador',
            'subtitulo' => 'Op. 100 Secado',
            'documentoid' => 'F7-SETCS-ELE-100-L1-03',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Cuarto Limpio 2',
            'linea' => 'Secador HMI',
            'operacion' => 100,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '926/970/959/971/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Set-up Checklist',
            'subtitulo' => '103 - Vacuum Bag',
            'documentoid' => 'F7-SETCS-ELE-103-L1-03',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / E. Lopez',
            'calidad' => 'R. Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 103,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo verificacion de maestros',
            'subtitulo' => 'Op. 107 Laser Etch',
            'documentoid' => 'F7-SETCS-ELE-107-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'Carlos Perez / Ulises Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Hector Maritnez / Rogelio Espinoza / Irineo Lopez',
            'area' => 'Cuarto Limpio',
            'linea' => 'OSP111/NH3/PM/OSM/PM RTD/OSL/OSMa/OSMaG2',
            'operacion' => 107,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo',
            'subtitulo' => 'Op. 107: RTD Etch',
            'documentoid' => 'F7-SETCS-ELE-107-L1-02',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / E. Lopez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 107,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist Set-up',
            'subtitulo' => 'Op. 120: Corte de ventana',
            'documentoid' => 'F7-SETCS-ELE-120-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'R. Guerrero',
            'manufactura' => 'G Espinoza / K. Mendoza / M. Loma',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 120,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist Set-up',
            'subtitulo' => 'Op. 140: Inserto de porous',
            'documentoid' => 'F7-SETCS-ELE-140-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes / C. Perez',
            'calidad' => 'R. Guerrero',
            'manufactura' => 'K. Mendoza / G. Espinoza / M. Loma',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 140,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959',
            'pagina' => '1 de 3',
            'numeroparte' => 'Ver hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Checklist de Parametros de Proceso',
            'subtitulo' => 'Op. 160: Stack and Tack',
            'documentoid' => 'F7-SETCS-ELE-160-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'Carlos P. / Ulises R. / Emmanuel L.',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'K. Mendoza / G. Espinoza / M. Loma',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 160,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => 'All',
            'pagina' => '1 of 4',
            'numeroparte' => 'Ver hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Set-up Checklist',
            'subtitulo' => 'Op. 180: Vacuum Bag',
            'documentoid' => 'F7-SETCS-ELE-180-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'Emmanuel Lopez / Ulises Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'K. Mendoza / M. Loma',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 180,
            'lugar' => 'Torreon',
            'planta' => 'plt 59',
            'departamento' => '971',
            'pagina' => '1 of 3',
            'numeroparte' => 'FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo',
            'subtitulo' => 'Op. 107: RTD Etch Layer 3',
            'documentoid' => 'F7-TPM-ELE-107-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'Ulises Reyes / Emmanuel Lopez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza / H. Martinez',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 107,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 of 3',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 40: Ponchado de hojas',
            'documentoid' => 'F7-TPM-ELE-40-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'U. Reyes / E. Lopez',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 40,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 2',
            'numeroparte' => '-',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo',
            'subtitulo' => 'Op. 60: Impresion',
            'documentoid' => 'F7-TPM-ELE-60-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'Emmanuel Lopez / Ulises Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Cuarto Limpio',
            'linea' => '1',
            'operacion' => 40,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/970/971/959/972',
            'pagina' => '1 de 3',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 100: Secado',
            'documentoid' => 'F7-TPM-ELE-100-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Clean Room',
            'linea' => '1',
            'operacion' => 100,
            'lugar' => 'TOR',
            'planta' => '59',
            'departamento' => '926/959/970/971/972',
            'pagina' => '1 de 1',
            'numeroparte' => 'See FM Sheet',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 120: Corte de ventana',
            'documentoid' => 'F7-TPM-ELE-120-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Clean Room',
            'linea' => '1',
            'operacion' => 140,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/959/970/971/972',
            'pagina' => '1 de 1',
            'numeroparte' => '1 de 1',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 140: Corte de Porous',
            'documentoid' => 'F7-TPM-ELE-140-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'R. Espinoza',
            'area' => 'Clean Room',
            'linea' => '1',
            'operacion' => 140,
            'lugar' => 'TOR',
            'planta' => '59',
            'departamento' => '926/959/970/971/972',
            'pagina' => '1 of 1',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 160: Stack & Tack',
            'documentoid' => 'F7-TPM-ELE-160-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Clean Room',
            'linea' => '1',
            'operacion' => 160,
            'lugar' => 'Torreon',
            'planta' => '59',
            'departamento' => '926/959/970/971/972',
            'pagina' => '1 of 1',
            'numeroparte' => 'Ver Hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
        Datoshoja::create([
            'titulo' => 'Hoja de chequeo de TPM',
            'subtitulo' => 'Op. 180: Vacuum bag',
            'documentoid' => 'F7-SETCS-ELE-180-L1-01',
            'numero_cambio' => '000',
            'fecha' => '1999-1-1',
            'revision' => '-',
            'meie' => 'E. Lopez / U. Reyes',
            'calidad' => 'Rodolfo Guerrero',
            'manufactura' => 'Rogelio Espinoza',
            'area' => 'Clean Room',
            'linea' => '1',
            'operacion' => 180,
            'lugar' => 'TOR',
            'planta' => '59',
            'departamento' => '926/959/970/971/972',
            'pagina' => '1 of 1',
            'numeroparte' => 'Ver hoja de FM',
            'mes' => 'Noviembre',
            'año' => 2022
        ]);
    }
}
